//
// Created by danilasar on 20.12.2024.
//

#include "RoadSystem.h"
#include "../../../utils.h"

#include <iostream>


namespace Game {
    namespace Systems {
        void RoadSystem::Redraw() {

            DrawRectangle(ROAD_VERTICAL_X, ROAD_VERTICAL_Y, ROAD_VERTICAL_W, ROAD_VERTICAL_H, DARKGRAY);
            DrawRectangle(ROAD_HORIZONTAL_X, ROAD_HORIZONTAL_Y, ROAD_HORIZONTAL_W, ROAD_HORIZONTAL_H, DARKGRAY);
            int i = 0;
            while((i + 1) * (MARKUP_LENGTH + MARKUP_SPACING) < ROAD_HORIZONTAL_Y - ROAD_ZEBRA_OUTER_HEIGHT) {
                DrawRectangle(ROAD_VERTICAL_X + ROAD_LEFT_LINE, ROAD_VERTICAL_Y + i * (MARKUP_LENGTH + MARKUP_SPACING), MARKUP_WIDTH, MARKUP_LENGTH, WHITE);
                DrawRectangle(ROAD_VERTICAL_X + ROAD_RIGHT_LINE, ROAD_VERTICAL_Y + i * (MARKUP_LENGTH + MARKUP_SPACING), MARKUP_WIDTH, MARKUP_LENGTH, WHITE);
                ++i;
            }
            i = 0;
            while((i + 1) * (MARKUP_LENGTH + MARKUP_SPACING) < ROAD_VERTICAL_X - ROAD_ZEBRA_OUTER_HEIGHT) {
                DrawRectangle(ROAD_HORIZONTAL_X + i * (MARKUP_LENGTH + MARKUP_SPACING), ROAD_HORIZONTAL_Y + ROAD_LEFT_LINE, MARKUP_LENGTH, MARKUP_WIDTH, WHITE);
                DrawRectangle(ROAD_HORIZONTAL_X + i * (MARKUP_LENGTH + MARKUP_SPACING), ROAD_HORIZONTAL_Y + ROAD_RIGHT_LINE, MARKUP_LENGTH, MARKUP_WIDTH, WHITE);
                ++i;
            }
            i = 0;
            while((i + 1) * (MARKUP_LENGTH + MARKUP_SPACING) < ROAD_VERTICAL_H - (ROAD_HORIZONTAL_Y + ROAD_WIDTH + ROAD_ZEBRA_OUTER_HEIGHT)) {
                DrawRectangle(ROAD_VERTICAL_X + ROAD_LEFT_LINE, ROAD_HORIZONTAL_Y + ROAD_WIDTH + ROAD_ZEBRA_OUTER_HEIGHT + i * (MARKUP_LENGTH + MARKUP_SPACING), MARKUP_WIDTH, MARKUP_LENGTH, WHITE);
                DrawRectangle(ROAD_VERTICAL_X + ROAD_RIGHT_LINE, ROAD_HORIZONTAL_Y + ROAD_WIDTH + ROAD_ZEBRA_OUTER_HEIGHT + i * (MARKUP_LENGTH + MARKUP_SPACING), MARKUP_WIDTH, MARKUP_LENGTH, WHITE);
                ++i;
            }
            i = 0;
            while((i + 1) * (MARKUP_LENGTH + MARKUP_SPACING) < ROAD_HORIZONTAL_W - (ROAD_VERTICAL_X + ROAD_WIDTH + ROAD_ZEBRA_OUTER_HEIGHT)) {
                DrawRectangle(ROAD_VERTICAL_X + ROAD_WIDTH + ROAD_ZEBRA_OUTER_HEIGHT + i * (MARKUP_LENGTH + MARKUP_SPACING), ROAD_HORIZONTAL_Y + ROAD_LEFT_LINE, MARKUP_LENGTH, MARKUP_WIDTH, WHITE);
                DrawRectangle(ROAD_VERTICAL_X + ROAD_WIDTH + ROAD_ZEBRA_OUTER_HEIGHT + i * (MARKUP_LENGTH + MARKUP_SPACING), ROAD_HORIZONTAL_Y + ROAD_RIGHT_LINE, MARKUP_LENGTH, MARKUP_WIDTH, WHITE);
                ++i;
            }
            DrawRectangle(ROAD_VERTICAL_X + ROAD_CENTRAL_MARKUP1, ROAD_VERTICAL_Y, MARKUP_WIDTH, ROAD_HORIZONTAL_Y - ROAD_VERTICAL_Y - ROAD_ZEBRA_OUTER_HEIGHT, WHITE);
            DrawRectangle(ROAD_VERTICAL_X + ROAD_CENTRAL_MARKUP2, ROAD_VERTICAL_Y, MARKUP_WIDTH, ROAD_HORIZONTAL_Y - ROAD_VERTICAL_Y - ROAD_ZEBRA_OUTER_HEIGHT, WHITE);
            DrawRectangle(ROAD_VERTICAL_X + ROAD_CENTRAL_MARKUP1, ROAD_HORIZONTAL_Y + ROAD_WIDTH + ROAD_ZEBRA_OUTER_HEIGHT, MARKUP_WIDTH, ROAD_VERTICAL_Y + ROAD_VERTICAL_H - ROAD_HORIZONTAL_Y - ROAD_ZEBRA_OUTER_HEIGHT, WHITE);
            DrawRectangle(ROAD_VERTICAL_X + ROAD_CENTRAL_MARKUP2, ROAD_HORIZONTAL_Y + ROAD_WIDTH + ROAD_ZEBRA_OUTER_HEIGHT, MARKUP_WIDTH, ROAD_VERTICAL_Y + ROAD_VERTICAL_H - ROAD_HORIZONTAL_Y - ROAD_ZEBRA_OUTER_HEIGHT, WHITE);
            DrawRectangle(ROAD_HORIZONTAL_X, ROAD_HORIZONTAL_Y + ROAD_CENTRAL_MARKUP1, ROAD_VERTICAL_X - ROAD_HORIZONTAL_X - ROAD_ZEBRA_OUTER_HEIGHT, MARKUP_WIDTH, WHITE);
            DrawRectangle(ROAD_HORIZONTAL_X, ROAD_HORIZONTAL_Y + ROAD_CENTRAL_MARKUP2, ROAD_VERTICAL_X - ROAD_HORIZONTAL_X - ROAD_ZEBRA_OUTER_HEIGHT, MARKUP_WIDTH, WHITE);
            DrawRectangle(ROAD_VERTICAL_X + ROAD_WIDTH + ROAD_ZEBRA_OUTER_HEIGHT, ROAD_HORIZONTAL_Y + ROAD_CENTRAL_MARKUP1, ROAD_HORIZONTAL_W - ROAD_VERTICAL_X - ROAD_ZEBRA_OUTER_HEIGHT, MARKUP_WIDTH, WHITE);
            DrawRectangle(ROAD_VERTICAL_X + ROAD_WIDTH + ROAD_ZEBRA_OUTER_HEIGHT, ROAD_HORIZONTAL_Y + ROAD_CENTRAL_MARKUP2, ROAD_HORIZONTAL_W - ROAD_VERTICAL_X - ROAD_ZEBRA_OUTER_HEIGHT, MARKUP_WIDTH, WHITE);
        }
    }
}